#import libraries
import pymysql
from sqlalchemy import create_engine

#database credentials
host=host
username=username
password=password
db='dermstore_data_challenge'

#connect to database
engine = create_engine('mysql+pymysql://'+username+':'+password+'@'+host+'/'+db)
connection = engine.connect()

#5 rows of random customer data
#no need to provide customer id or date_created value. these are auto-generated by table schema
insert = 'INSERT INTO customers (customer_firstname, customer_lastname,customer_email) VALUES(?,?,?)'
values1 = ('Homer','Simpson','homer.simpson@gmail.com')
values2 = ('Marge','Simpson','marge.simpson@gmail.com')
values3 = ('Bart','Simpson','bart.simpson@gmail.com')
values4 = ('Lisa','Simpson','lisa.simpson@gmail.com')
values5 = ('Maggie','Simpson','maggie.simpson@gmail.com')

#execute insert statements
engine.execute(insert,values1)
engine.execute(insert,values2)
engine.execute(insert,values3)
engine.execute(insert,values4)
engine.execute(insert,values5)

connection.close()